### ISSUE TITLE
The STL files

### ISSUE THREAD

**Issue by manojngb** [jochenalt/Donna#1]
Hi Jochen, 
   This is a great project. I would like to demo this to school kids to elicit interest in them for robotics.  However there are CAD parts in different folder with same name, making it hard for me to choose the correct ones.  For ex: Rose/code/Client/stl/ and Rose/CAD/Chickenhead/, CAD/STL and CAD/... .  Could  you help in segregating them. Thanks

**Comment by jochenalt** [comment]
Hi,
Chickenhead and Client/stl are simplified shapes for the opengl simulation, the relevant files for 3D print are in CAD/stl 
Cheers
